update detached header support in cryptdisks, add it to cryptroot initramfs scripts

diff --git a/debian/initramfs/cryptroot-hook b/debian/initramfs/cryptroot-hook
--- a/debian/initramfs/cryptroot-hook
+++ b/debian/initramfs/cryptroot-hook
@@ -173,6 +173,7 @@ get_device_opts() {
 	target="$1"
 	extraopts="$2"
 	KEYSCRIPT=""
+	CRYPTHEADER=""
 	OPTIONS=""
 
 	if [ -z "$target" ]; then
@@ -224,29 +225,14 @@ get_device_opts() {
 			cipher=*)
 				OPTIONS="$OPTIONS,$opt"
 				;;
+			size=*)
+				OPTIONS="$OPTIONS,$opt"
+				;;
 			hash=*)
 				OPTIONS="$OPTIONS,$opt"
 				HASH_FOUND=1
 				;;
-			size=*)
-				OPTIONS="$OPTIONS,$opt"
-				;;
-			lvm=*)
-				OPTIONS="$OPTIONS,$opt"
-				;;
-			keyscript=*)
-				opt=${opt#keyscript=}
-				if [ ! -x "/lib/cryptsetup/scripts/$opt" ] && [ ! -x "$opt" ]; then
-					echo "cryptsetup: WARNING: target $target has an invalid keyscript, skipped" >&2
-					return 1
-				fi
-				KEYSCRIPT="$opt"
-				OPTIONS="$OPTIONS,keyscript=/lib/cryptsetup/scripts/$(basename "$opt")"
-				;;
 			tries=*)
-				OPTIONS="$OPTIONS,$opt"
-				;;
-			rootdev)
 				OPTIONS="$OPTIONS,$opt"
 				;;
 			discard)
@@ -255,7 +241,31 @@ get_device_opts() {
 			luks)
 				LUKS_FOUND=1
 				;;
+			header)
+				opt="${opt#header=}"
+				if [ ! -e "$opt" ]; then
+					echo "cryptsetup: WARNING: target $target has an invalid header, skipped" >&2
+					return 1
+				fi
+				CRYPTHEADER="$opt"
+				OPTIONS="$OPTIONS,header="$CRYPTHEADER")"
+				;;
 			tcrypt)
+				OPTIONS="$OPTIONS,$opt"
+				;;
+			keyscript=*)
+				opt="${opt#keyscript=}"
+				if [ ! -x "/lib/cryptsetup/scripts/$opt" ] && [ ! -x "$opt" ]; then
+					echo "cryptsetup: WARNING: target $target has an invalid keyscript, skipped" >&2
+					return 1
+				fi
+				KEYSCRIPT="$opt"
+				OPTIONS="$OPTIONS,keyscript=/lib/cryptsetup/scripts/$(basename "$opt")"
+				;;
+			lvm=*)
+				OPTIONS="$OPTIONS,$opt"
+				;;
+			rootdev)
 				OPTIONS="$OPTIONS,$opt"
 				;;
 			*)
@@ -270,6 +280,12 @@ get_device_opts() {
 		echo "         If this is wrong, this initramfs image will not boot." >&2
 		echo "         Please read /usr/share/doc/cryptsetup/README.initramfs.gz and add" >&2
 		echo "         the correct hash option to your /etc/crypttab."  >&2
+	fi
+
+	# Warn that header only applies to a LUKS partition currently
+	if [ -n "$CRYPTHEADER" ] && [ -z "$LUKS_FOUND" ]; then
+		echo "WARNING: Option LUKS missing in crypttab for target $target." >&2
+		echo "         Headers are only supported for LUKS devices." >&2
 	fi
 
 	# If keyscript is set, the "key" is just an argument to the script
@@ -427,6 +443,25 @@ add_device() {
 				continue
 			fi
 		fi
+
+		# If we have a LUKS header, make sure it is included
+		# TODO: make it configurable to include the LUKS header into initramfs
+		# disabled for now due to security reasons
+		if [ -n "$CRYPTHEADER" ]; then
+			if [ ! -d "$DESTDIR/conf/conf.d/cryptheader" ]; then
+				mkdir -p "$DESTDIR/conf/conf.d/cryptheader"
+			fi
+
+			#if [ -e "$CONFDIR/conf.d/cryptheader/$CRYPTHEADER" ]; then
+			#	copy_exec "$CONFDIR/conf.d/cryptheader/$CRYPTHEADER" /conf/conf.d/cryptheader >&2
+			#elif [ -e "$CRYPTHEADER" ]; then
+			#	copy_exec "$CRYPTHEADER" /conf/conf.d/cryptheader >&2
+			#else
+			#	echo "cryptsetup: WARNING: failed to find LUKS header $CRYPTHEADER" >&2
+			#	continue
+			#fi
+		fi
+		
 
 		# Calculate needed modules
 		modules=$(get_device_modules $node | sort | uniq)
