several bugfixes, missed to push them one by one

diff --git a/debian/initramfs/cryptroot-hook b/debian/initramfs/cryptroot-hook
--- a/debian/initramfs/cryptroot-hook
+++ b/debian/initramfs/cryptroot-hook
@@ -16,7 +16,7 @@ esac
 
 . /usr/share/initramfs-tools/hook-functions
 
-get_root_device() {
+get_root_devices() {
 	local device mount type options dump pass
 
 	if [ ! -r /etc/fstab ]; then
@@ -26,15 +26,22 @@ get_root_device() {
 	grep -s '^[^#]' /etc/fstab | \
 	while read device mount type options dump pass; do
 		if [ "$mount" = "/" ]; then
-			device=$(canonical_device "$device") || return 0
-			echo "$device"
+			local devices
+			if [ "$type" = "btrfs" ]; then
+				for dev in $(btrfs filesystem show $(canonical_device "$device" --no-simplify) 2>/dev/null | sed -r -e 's/.*devid .+ path (.+)/\1/;tx;d;:x') ; do
+					devices="$devices $(canonical_device "$dev")"
+				done
+			else
+				devices=$(canonical_device "$device") || return 0
+			fi
+			echo "$devices"
 			return
 		fi
 	done
 }
 
 get_resume_devices() {
-	local device opt count dupe candidates devices
+	local device opt count dupe candidates devices derived
 	candidates=""
 
 	# First, get a list of potential resume devices
@@ -86,16 +93,9 @@ get_resume_devices() {
 		fi
 
 		# Detect devices required by decrypt_derived
-		derived="$(grep "^${device#/dev/mapper/}\b.*decrypt_derived" /etc/crypttab 2>/dev/null | awk '{print $3}')"
+		derived=$(get_derived_device "$device")
 		if [ -n "$derived" ]; then
-			if grep -q "^$derived" /etc/crypttab; then
-				derived=$(canonical_device "/dev/mapper/$derived") || return 0
-				if [ "$derived" != "$rootdev" ]; then
-					devices="$devices $derived"
-				fi
-			else
-				echo "cryptsetup: WARNING: decrypt_derived device $derived not found in crypttab" >&2
-			fi
+			devices="$devices $derived"
 		fi
 
 		device=$(canonical_device "$device") || return 0
@@ -128,6 +128,68 @@ get_resume_devices() {
 	fi
 
 	return 0
+}
+
+get_initramfs_devices() {
+	local device opt count dupe target source key options candidates devices derived
+
+	candidates="$(grep -s '^[^#]' /etc/crypttab | \
+	while read target source key options; do
+		if echo $options | grep -q "\binitramfs\b"; then
+			echo " /dev/mapper/$target"
+		fi
+	done;)"
+
+	devices=""
+	count=0
+	for device in $candidates; do
+		# Detect devices required by decrypt_derived
+		derived=$(get_derived_device "$device")
+		if [ -n "$derived" ]; then
+			devices="$devices $derived"
+		fi
+
+		device=$(canonical_device "$device") || return 0
+
+		# Weed out duplicates
+		dupe=0
+		for opt in $devices; do
+			if [ "$device" = "$opt" ]; then
+				dupe=1
+			fi
+		done
+		if [ $dupe -eq 1 ]; then
+			continue
+		fi
+
+		# This device seems ok
+		devices="$devices $device"
+		count=$(( $count + 1 ))
+	done
+
+	if [ $count -gt 0 ]; then
+		echo $devices
+	fi
+
+	return 0
+}
+
+get_derived_device() {
+	# Detect device required by decrypt_derived
+	local device derived
+	device="$1"
+
+	derived="$(grep "^${device#/dev/mapper/}\b.*decrypt_derived" /etc/crypttab 2>/dev/null | awk '{print $3}')"
+	if [ -n "$derived" ]; then
+		if grep -q "^$derived\b" /etc/crypttab; then
+			derived=$(canonical_device "/dev/mapper/$derived") || return 0
+			if ! echo "$rootdevs" | grep -q "\b$derived\b"; then
+				echo "$derived"
+			fi
+		else
+			echo "cryptsetup: WARNING: decrypt_derived device $derived not found in crypttab" >&2
+		fi
+	fi
 }
 
 node_is_in_crypttab() {
@@ -324,6 +386,7 @@ get_device_modules() {
 canonical_device() {
 	local dev altdev original
 	dev="$1"
+	opt="$2"
 
 	altdev="${dev#LABEL=}"
 	if [ "$altdev" != "$dev" ]; then
@@ -338,6 +401,11 @@ canonical_device() {
 	original="$dev"
 	if [ -h "$dev" ]; then
 		dev=$(readlink -e "$dev")
+	fi
+
+	if [ "$opt" = "--no-simplify" ]; then
+		echo "$dev"
+		return 0
 	fi
 
 	if [ "x${dev%/dev/dm-*}" = "x" ]; then
@@ -375,7 +443,7 @@ add_device() {
 	fi
 
 	# Flag root device
-	if [ "$nodes" = "$rootdev" ]; then
+	if echo "$rootdevs" | grep -q "\b$nodes\b"; then
 		if [ -z "$opts" ]; then
 			opts="rootdev"
 		else
@@ -542,7 +610,7 @@ add_crypto_modules() {
 #
 
 setup="no"
-rootdev=""
+rootdevs=""
 resumedevs=""
 
 # Include cryptsetup modules, regardless of _this_ machine
@@ -553,15 +621,16 @@ fi
 
 # Find the root and resume device(s)
 if [ -r /etc/crypttab ]; then
-	rootdev=$(get_root_device)
-	if [ -z "$rootdev" ]; then
+	rootdevs=$(get_root_devices)
+	if [ -z "$rootdevs" ]; then
 		echo "cryptsetup: WARNING: could not determine root device from /etc/fstab" >&2
 	fi
 	resumedevs=$(get_resume_devices)
+	initramfsdevs=$(get_initramfs_devices)
 fi
 
 # Load the config opts and modules for each device
-for dev in $rootdev $resumedevs; do
+for dev in $rootdevs $resumedevs $initramfsdevs; do
 	if ! modules=$(add_device "$dev"); then
 		echo "cryptsetup: FAILURE: could not determine configuration for $dev" >&2
 		continue
