initramfs: Add support for multiple devices encrypted using a gpg-encrypted key.

diff --git a/debian/initramfs/cryptgnupg-hook b/debian/initramfs/cryptgnupg-hook
--- a/debian/initramfs/cryptgnupg-hook
+++ b/debian/initramfs/cryptgnupg-hook
@@ -27,22 +27,20 @@ if [ ! -x ${DESTDIR}/lib/cryptsetup/scripts/decrypt_gnupg ] ; then
 fi
 
 # Install cryptroot key files into initramfs
-keys=$(sed 's/^\(.*,\|\)key=//; s/,.*//' ${DESTDIR}/conf/conf.d/cryptroot)
+keys="$( awk '$4 ~ /^(.*,)?keyscript=([^,]*\/)?decrypt_gnupg(,.*)?$/ {print $3}' \
+			/etc/crypttab )"
 
-if [ "${keys}" != "none" ]; then
-    if [ -z "${keys}" ]; then
-        echo "$0: Missing key files in ${DESTDIR}/conf/conf.d/cryptroot" >&2
-        cat ${DESTDIR}/conf/conf.d/cryptroot >&2
-        exit 1
-    fi
-    for key in ${keys} ; do
-	echo "WARNING: gpg-encrypted key $key is copied to initramfs" >&2
-        if [ ! -d ${DESTDIR}/$(dirname ${key}) ] ; then
-            mkdir -p ${DESTDIR}/$(dirname ${key})
-        fi
-        cp ${key} ${DESTDIR}/${key}
-    done
+if [ -z "$keys" ]; then
+	echo "$0: Missing key files in ${DESTDIR}/conf/conf.d/cryptroot" >&2
+	cat "${DESTDIR}/conf/conf.d/cryptroot" >&2
+	exit 1
 fi
+
+for key in $keys; do
+	echo "WARNING: gpg-encrypted key $key is copied to initramfs" >&2
+	mkdir -p "${DESTDIR}/$(dirname ${key})"
+	cp -f "$key" "${DESTDIR}/${key}"
+done
 
 # Install gnupg software
 copy_exec /usr/bin/gpg
