Change the initramfs script to use askpass to prompt for passphrases, this should hopefully fix #382375 and #465902 once it is enabled in the init scripts as well.

diff --git a/debian/initramfs/cryptroot-script b/debian/initramfs/cryptroot-script
--- a/debian/initramfs/cryptroot-script
+++ b/debian/initramfs/cryptroot-script
@@ -25,6 +25,27 @@ esac
 #
 # Helper functions
 #
+message()
+{
+	if [ -p /dev/.initramfs/usplash_outfifo ] && [ -x /sbin/usplash_write ]; then
+		usplash_write "TEXT-URGENT $@"
+	else
+		echo "$@" >&2
+	fi
+	return 0
+}
+
+udev_settle()
+{
+	# Wait for udev to be ready, see https://launchpad.net/bugs/85640
+	if [ -x /sbin/udevadm ]; then
+		/sbin/udevadm settle --timeout=30
+	elif [ -x /sbin/udevsettle ]; then
+		/sbin/udevsettle --timeout=30
+	fi
+	return 0
+}
+
 parse_options()
 {
 	local cryptopts
@@ -41,7 +62,7 @@ parse_options()
 	crypttarget=cryptroot
 	cryptsource=""
 	cryptlvm=""
-	cryptkeyscript=""
+	cryptkeyscript="/lib/cryptsetup/askpass"
 	cryptkey="" # This is only used as an argument to an eventual keyscript
 	crypttries=3
 
@@ -91,7 +112,7 @@ parse_options()
 	done
 
 	if [ -z "$cryptsource" ]; then
-		echo "cryptsetup: source parameter missing"
+		message "cryptsetup: source parameter missing"
 		return 1
 	fi
 	return 0
@@ -153,6 +174,11 @@ setup_mapping()
 
 	parse_options "$opts" || return 1
 
+	if [ -z "$cryptkeyscript" ] || [ ! -x "$cryptkeyscript" ]; then
+		message "cryptsetup: error - script \"$cryptkeyscript\" missing"
+		return 1
+	fi
+
 	# The same target can be specified multiple times
 	# e.g. root and resume lvs-on-lvm-on-crypto
 	if [ -e "/dev/mapper/$crypttarget" ]; then
@@ -160,22 +186,17 @@ setup_mapping()
 	fi
 
 	modprobe -q dm_crypt
-	echo "Setting up cryptographic volume $crypttarget (based on $cryptsource)"
 
 	# Make sure the cryptsource device is available
 	if [ ! -e $cryptsource ]; then
 		activate_vg $cryptsource
 		activate_evms $cryptsource
 	fi
-	# Wait for udev to be ready, see https://launchpad.net/bugs/85640
-	if [ -x /sbin/udevadm ]; then
-		/sbin/udevadm settle --timeout=30
-	elif [ -x /sbin/udevsettle ]; then
-		/sbin/udevsettle --timeout=30
-	fi
+
+	udev_settle
 
 	if [ ! -e $cryptsource ]; then
-		echo "cryptsetup: Source device $cryptsource not found"
+		message "cryptsetup: source device $cryptsource not found"
 		return 1
 	fi
 
@@ -188,37 +209,29 @@ setup_mapping()
 	cryptremove="/sbin/cryptsetup remove $crypttarget"
 	NEWROOT="/dev/mapper/$crypttarget"
 
-	# Try to get a satisfactory password three times
+	# Try to get a satisfactory password $crypttries times
 	count=0
 	while [ $crypttries -le 0 ] || [ $count -lt $crypttries ]; do
 		count=$(( $count + 1 ))
 
-		if [ -n "$cryptkeyscript" ]; then
-			if [ ! -x "$cryptkeyscript" ]; then
-				echo "cryptsetup: error - $cryptkeyscript missing"
-				return 1
-			fi
-			crypttarget="$crypttarget" cryptsource="$cryptsource" \
-			$cryptkeyscript $cryptkey < /dev/console 2> /dev/console | \
-			$cryptcreate --key-file=- > /dev/console 2>&1
-		elif [ -p /dev/.initramfs/usplash_outfifo ] && [ -x /sbin/usplash_write ]; then
-			usplash_write "INPUTQUIET Enter password for $crypttarget: "
-			PASS="$(cat /dev/.initramfs/usplash_outfifo)"
-			echo -n "$PASS" | $cryptcreate > /dev/null 2>&1
-		else
-			$cryptcreate < /dev/console > /dev/console 2>&1
+		if [ $count -gt 1 ]; then
+			sleep 3
 		fi
 
-		if [ $? -ne 0 ]; then
-			echo "cryptsetup: cryptsetup failed, bad password or options?"
-			sleep 3
-			continue
-		elif [ ! -e "$NEWROOT" ]; then
-			echo "cryptsetup: unknown error setting up device mapping"
+		if [ $crypttries -gt 0 ] && [ $count -gt $crypttries ]; then
+			message "cryptsetup: maximum number of tries exceeded for $crypttarget"
 			return 1
-		elif [ -p /dev/.initramfs/usplash_outfifo ] && [ -x /sbin/usplash_write ]; then
-			# clean the text, to give feedback that it worked
-			usplash_write "TEXT-URGENT "
+		fi
+
+		if ! crypttarget="$crypttarget" cryptsource="$cryptsource" \
+		     $cryptkeyscript "$cryptkey" | $cryptcreate --key-file=- ; then
+			message "cryptsetup: cryptsetup failed, bad password or options?"
+			continue
+		fi
+
+		if [ ! -e "$NEWROOT" ]; then
+			message "cryptsetup: unknown error setting up device mapping"
+			return 1
 		fi
 
 		FSTYPE=''
@@ -227,10 +240,10 @@ setup_mapping()
 		# See if we need to setup lvm on the crypto device
 		if [ "$FSTYPE" = "lvm" ] || [ "$FSTYPE" = "lvm2" ]; then
 			if [ -z "$cryptlvm" ]; then
-				echo "cryptsetup: lvm fs found but no lvm configured"
+				message "cryptsetup: lvm fs found but no lvm configured"
 				return 1
 			elif ! activate_vg "/dev/mapper/$cryptlvm"; then
-				echo "cryptsetup: failed to setup lvm device"
+				message "cryptsetup: failed to setup lvm device"
 				return 1
 			fi
 
@@ -239,25 +252,17 @@ setup_mapping()
 		fi
 
 		if [ -z "$FSTYPE" ] || [ "$FSTYPE" = "unknown" ]; then
-			echo "cryptsetup: unknown fstype, bad password or options?"
+			message "cryptsetup: unknown fstype, bad password or options?"
 			$cryptremove
-			sleep 3
 			continue
 		fi
 
+		message "cryptsetup: $crypttarget setup successfully"
 		break
 	done
 
-	if [ $count -lt 3 ]; then
-		# Wait for udev to be ready, see https://launchpad.net/bugs/85640
-		if [ -x /sbin/udevsettle ]; then
-			/sbin/udevsettle --timeout=30
-		fi
-		return 0
-	else
-		echo "cryptsetup: maximum number of tries exceeded"
-		return 1
-	fi
+	udev_settle
+	return 0
 }
 
 #
@@ -281,9 +286,9 @@ fi
 
 # Do we have any settings from the /conf/conf.d/cryptroot file?
 if [ -r /conf/conf.d/cryptroot ]; then
-	while read mapping; do
+	while read mapping <&3; do
 		setup_mapping "$mapping"
-	done < /conf/conf.d/cryptroot
+	done 3< /conf/conf.d/cryptroot
 fi
 
 exit 0
