merge prechecks and postchecks

diff --git a/debian/cryptsetup.cryptdisks.init b/debian/cryptsetup.cryptdisks.init
--- a/debian/cryptsetup.cryptdisks.init
+++ b/debian/cryptsetup.cryptdisks.init
@@ -25,6 +25,8 @@ test -f $TABFILE   || exit 0
 
 [ -r /etc/default/cryptdisks ] && . /etc/default/cryptdisks
 
+[ -r /lib/cryptsetup/init_functions ] && . /lib/cryptsetup/init_functions
+
 case "$CRYPTDISKS_ENABLE" in
   [Nn]*)
   	exit 0
@@ -32,155 +34,6 @@ case "$CRYPTDISKS_ENABLE" in
 esac
 
 $DEVMAPCMD mknodes
-
-parse_opts () {
-	PARAMS=""
-	POSTCHECK=""
-	PRECHECK=""
-	RETRY="no"
-	MAKETMP=""
-	MAKESWAP=""
-	USELUKS=""
-	SKIP=""
-	TIMEOUT=""
-
-	# Parse the options field, convert to cryptsetup parameters
-	# and contruct the command line
-	while test "x$opt" != "x" ; do
-		ARG=`echo $opt | sed "s/,.*//"`
-		opt=${opt##$ARG}
-		opt=${opt##,}
-		PARAM=`echo $ARG | sed "s/=.*//"`
-		
-		case "$ARG" in
-		  *=*)
-		  	PARAM=`echo $ARG | sed "s/=.*//"`
-		  	VALUE=${ARG##$PARAM=}
-		  	;;
-		  *)
-		  	PARAM=$ARG
-		  	VALUE=""
-			;;
-		esac
-		
-		case "$PARAM" in 
-		  readonly)
-		  	PARAMS="$PARAMS -r"
-		  	;;
-		  cipher)
-		  	PARAMS="$PARAMS -c $VALUE"
-		  	if test "x$VALUE" = "x" ; then
-		  		echo -e "\n - no value for cipher option, skipping" >&2
-		  		SKIP="yes"
-		  	fi
-		  	;;
-		  size)
-		  	PARAMS="$PARAMS -s $VALUE"
-		  	if test "x$VALUE" = "x" ; then
-		  		echo -e "\n - no value for size option, skipping" >&2
-		  		SKIP="yes"
-		  	fi
-		  	;;
-		  hash)
-		  	PARAMS="$PARAMS -h $VALUE"
-		  	if test "x$VALUE" = "x" ; then
-		  		echo -e "\n - no value for hash option, skipping" >&2
-		  		SKIP=yes
-		  	fi
-		  	;;
-		  verify)
-		  	PARAMS="$PARAMS -y"
-		  	;;
-		  postcheck)
-		  	if test "x$VALUE" = "x" ; then
-		  		POSTCHECK="$CRYPTDISKS_POSTCHECK"
-		  	else
-		  		POSTCHECK="$VALUE"
-		  	fi
-		  	if [ "$POSTCHECK" -a -x /lib/cryptsetup/postchecks/"$POSTCHECK" ]; then
-		   		POSTCHECK="/lib/cryptsetup/postchecks/$POSTCHECK"
-		  	else
-		  		POSTCHECK=""
-		  	fi
-		  	;;
-		  precheck)
-		  	if test "x$VALUE" = "x" ; then
-		  		PRECHECK="$CRYPTDISKS_PRECHECK"
-		  	else
-		  		PRECHECK="$VALUE"
-		  	fi
-		   	if [ "$PRECHECK" -a -x /lib/cryptsetup/prechecks/"$PRECHECK" ]; then
-		  		PRECHECK="/lib/cryptsetup/prechecks/$PRECHECK"
-		  	else
-		  		PRECHECK=""
-		  	fi
-		  	;;
-		  retry)
-		  	if test "x$VALUE" = "x" ; then
-		  		RETRY="$CRYPTDISKS_RETRY"
-		  	else
-		  		RETRY="$VALUE"
-		  	fi
-		  	case "$RETRY" in
-		  	  no|[0-9]*)
-		  	  	;;
-		  	  *)
-			  	echo " - option RETRY is wrongly set to $RETRY - forced to 'no' " >&2
-			  	RETRY="no"
-			  	;;
-			esac
-		  	;;
-		  timeout)
-		  	if test "x$VALUE" = "x" ; then
-		  		TIMEOUT="$CRYPTDISKS_TIMEOUT"
-		  	else
-		  		TIMEOUT="$VALUE"
-		  	fi
-		  	PARAMS="$PARAMS --timeout $TIMEOUT"
-		  	;;
-		  swap)
-		  	MAKESWAP=yes
-		  	;;
-		  tmp)
-		  	MAKETMP=yes
-		  	;;
-		  luks)
-		  	USELUKS=yes
-			;;
-		  loud)
-		  	LOUD=yes
-		esac
-	done
-
-	# Password processing in luks* from cryptsetup is newline sensitive
-	# reading stops after \n is received!
-	if test "x$USELUKS" = "xyes" && \
-	   test "x$MAKESWAP" = "xyes" && \
-	   test "x$INTERACTIVE" != "xyes"; then
-		echo -e "\n - you should not mix swap and luks, skipping" >&2
-		continue
-	fi
-}
-
-lo_setup () {
-	# Set up loopback devices
-	if test -f "$src" ; then
-		test -d /sys/block/loop0 || modprobe loop || SKIP=yes
-		LOOP_ID=
-		for i in 0 1 2 3 4 5 6 7 ; do
-			if test "x`cat /sys/block/loop$i/size`" = "x0" ; then
-				LOOP_ID=$i
-				break
-			fi
-		done
-		if test "x$LOOP_ID" = "x" ; then
-			SKIP=yes
-		else
-			$LOSETUP /dev/loop$LOOP_ID $src || SKIP=yes
-			src=/dev/loop$LOOP_ID
-		fi
-	fi
-}
 
 case "$1" in
   start)
@@ -241,10 +94,10 @@ case "$1" in
 							RESULT=$?
 						fi
 						if [ $RESULT = 0 ] ; then
-							if [ "$POSTCHECK" = ""  ] || $POSTCHECK $MAPPER/$dst ; then
+							if [ "$CHECK" = ""  ] || $CHECK $MAPPER/$dst ; then
 								break
 							else
-								echo " - the postcheck for '$MAPPER/$dst' failed" >&2
+								echo " - the check for '$MAPPER/$dst' failed" >&2
 								#echo " - removing the crypto device $dst" >&2
 								#$CRYPTCMD luksClose $dst
 								sleep 1
@@ -270,10 +123,10 @@ case "$1" in
 							RESULT=$?
 						fi
 						if [ $RESULT = 0 ] ; then
-							if [ "$POSTCHECK" = ""  ] || $POSTCHECK $MAPPER/$dst ; then
+							if [ "$CHECK" = ""  ] || $CHECK $MAPPER/$dst ; then
 								break
 							else
-								echo " - the postcheck for '$MAPPER/$dst' failed - maybe the password is wrong" >&2
+								echo " - the check for '$MAPPER/$dst' failed - maybe the password is wrong" >&2
 								echo " - removing the crypto device $dst" >&2
 								$CRYPTCMD remove $dst
 								sleep 1
