Support root-on-crypto-on-lvm without having the change the root variable

diff --git a/debian/initramfs-cryptroot-script b/debian/initramfs-cryptroot-script
--- a/debian/initramfs-cryptroot-script
+++ b/debian/initramfs-cryptroot-script
@@ -90,24 +90,33 @@ get_options()
 	fi
 }
 
-setup_lvm()
+activate_vg()
 {
-	local cryptlvm
-	cryptlvm=$1
+	local vg
+	vg=$1
 
-	if [ -z "$cryptlvm" ]; then
-		panic "found lvm pv on encrypted device but no lvm option set"
+	# Sanity checks
+	if [ ! -x /sbin/vgchange ]; then
+		return 1
 	fi
-	NEWROOT="/dev/mapper/${cryptlvm}"
+
+	if [ -z "$vg" ]; then
+		return 1
+	fi
+
+	# Make sure we're dealing with a lvm device
+	vg=${vg#/dev/mapper/}
+	if [ "$vg" = "$1" ]; then
+		return 1
+	fi
+
 	# Split volume group from logical volume.
-	cryptlvm=$(echo ${cryptlvm} | sed -e 's#\(.*\)\([^-]\)-[^-].*#\1\2#')
+	vg=$(echo ${vg} | sed -e 's#\(.*\)\([^-]\)-[^-].*#\1\2#')
 	# Reduce padded --'s to -'s
-	cryptlvm=$(echo ${cryptlvm} | sed -e 's#--#-#g')
-	vgchange -ay ${cryptlvm}
-	if ! fstype < "$NEWROOT" > /conf/param.conf; then
-		panic "failed to setup lvm device, fs not recognised"
-	fi
-	. /conf/param.conf
+	vg=$(echo ${vg} | sed -e 's#--#-#g')
+
+	vgchange -ay ${vg}
+	return $?
 }
 
 
@@ -117,13 +126,22 @@ setup_lvm()
 
 # define crypto variables
 get_options
+
+# make sure the cryptsource device is available
+if [ ! -e $cryptsource ]; then
+	activate_vg $cryptsource
+fi
+if [ ! -e $cryptsource ]; then
+	panic "$0: source device $cryptsource not found"
+fi
+
+# prepare commands
 if /sbin/cryptsetup isLuks $cryptsource > /dev/null 2>&1; then
 	cryptcreate="/sbin/cryptsetup luksOpen $cryptsource $crypttarget"
-	cryptremove=""
 else
 	cryptcreate="/sbin/cryptsetup -c $cryptcipher -s $cryptsize -h $crypthash create $crypttarget $cryptsource"
-	cryptremove="/sbin/cryptsetup remove $crypttarget"
 fi
+cryptremove="/sbin/cryptsetup remove $crypttarget"
 NEWROOT="/dev/mapper/$crypttarget"
 
 # Loop until we have a satisfactory password
@@ -134,20 +152,32 @@ while [ 1 ]; do
 		$cryptcreate < /dev/console
 	fi
 
-	if [ $? -eq 0 ] && fstype < "$NEWROOT" > /conf/param.conf; then
+	FSTYPE=''
+	if [ $? -ne 0 ]; then
+		echo "$0: cryptsetup failed, bad password or options?"
+	elif ! fstype < "$NEWROOT" > /conf/param.conf; then
+		echo "$0: fstype not recognized, bad password or options?"
+	else
 		. /conf/param.conf
 
+		# See if we need to setup lvm on the crypto device
 		if [ "$FSTYPE" = "lvm" ] || [ "$FSTYPE" = "lvm2" ]; then
-			setup_lvm "$cryptlvm"
-		fi
-
-		if [ "$FSTYPE" != "unknown" ]; then
-			break
+			NEWROOT="/dev/mapper/$cryptlvm"
+			activate_vg "$NEWROOT" || panic "failed to setup lvm device"
+			if ! fstype < "$NEWROOT" > /conf/param.conf; then
+				panic "failed to setup lvm device, fs not recognised"
+			fi
+			. /conf/param.conf
 		fi
 	fi
 
-	echo "$0: cryptsetup failed or fstype not recognized, bad password or options?"
-	$cryptremove
+	if [ -n "$FSTYPE" ] && [ "$FSTYPE" != "unknown" ]; then
+		break
+	fi
+
+	if [ -e "$NEWROOT" ]; then
+		$cryptremove
+	fi
 	sleep 3
 done
 
