rewrite error code handling in handle_crypttab_line_* and cryptdisks_{start|stop}

diff --git a/debian/scripts/cryptdisks_start b/debian/scripts/cryptdisks_start
--- a/debian/scripts/cryptdisks_start
+++ b/debian/scripts/cryptdisks_start
@@ -7,7 +7,7 @@
 # License: GNU General Public License, v2 or any later
 # (http://www.gnu.org/copyleft/gpl.html)
 
-set -e
+# don't set -e, check exit status instead
 
 if [ $# -lt 1 ]; then
 	echo "usage: $0 <name>" >&2
@@ -27,18 +27,20 @@ LOUD="yes"
 log_action_begin_msg "Starting crypto disk"
 mount_fs
 
-found="no"
+count=0
+tablen="$(egrep -v "^[[:space:]]*(#|$)" "$TABFILE" | /usr/bin/wc -l)"
 egrep -v "^[[:space:]]*(#|$)" "$TABFILE" | while read dst src key opts; do
+	count=$(( $count + 1 ))
 	if [ "$1" = "$dst" ]; then
-		found="yes"
 		handle_crypttab_line_start "$dst" "$src" "$key" "$opts" <&3
-		exit 0
+		exit $?
+	fi
+	if [ $count -ge $tablen ]; then
+		device_msg "$1" "failed, not found in crypttab"
+		exit 1
 	fi
 done 3<&1
-
-if [ "$found" = "no" ]; then
-	device_msg "$1" "failed, not found in crypttab"
-fi
+ret=$?
 
 umount_fs
-log_action_end_msg 0
+log_action_end_msg $ret
