more fixes to decrypt_openct

diff --git a/debian/scripts/decrypt_openct b/debian/scripts/decrypt_openct
--- a/debian/scripts/decrypt_openct
+++ b/debian/scripts/decrypt_openct
@@ -20,7 +20,7 @@ wait_reader() {
     echo "Waiting for Smart Card reader..." >&2
     /usr/bin/openct-tool rwait >/dev/null 2>&1
     if [ $? != 0 ]; then
-        echo "Failed to find Smart Card reader!" >&2
+        echo 'Failed to find Smart Card reader!' >&2
     fi
 #    if [ $readerfound = 0 ] ; then
 #        tries=0
@@ -31,7 +31,7 @@ wait_reader() {
 #            tries=$(($tries + 1))
 #        done
 #        if [ $readerfound = 0 ] ; then
-#            echo "Failed to find Smart Card reader!" >&2
+#            echo 'Failed to find Smart Card reader!' >&2
 #            exit 1
 #        fi
 #    fi
@@ -41,7 +41,7 @@ wait_card() {
     echo "Waiting for Smart Card..." >&2
     /usr/bin/openct-tool wait >/dev/null 2>&1
     if [ $? != 0 ]; then
-        echo "Failed to find Smart Card!" >&2
+        echo 'Failed to find Smart Card!' >&2
     fi
 }
 
diff --git a/debian/scripts/decrypt_opensc b/debian/scripts/decrypt_opensc
--- a/debian/scripts/decrypt_opensc
+++ b/debian/scripts/decrypt_opensc
@@ -21,7 +21,7 @@ check_card() {
 wait_card() {
     check_card
     if [ $cardfound == 0 ] ; then
-        echo Waiting for Smart Card... >&2
+        echo "Waiting for Smart Card..." >&2
         tries=0
         while [ $cardfound == 0 -a $tries -lt 60 ] ; do
             sleep 1
@@ -29,7 +29,7 @@ wait_card() {
             tries=$(($tries + 1))
         done
         if [ $cardfound == 0 ] ; then
-            echo Failed to find Smart Card card!
+            echo 'Failed to find Smart Card card!' >&2
             exit 1
         fi
     fi
